version: "3.9"
services:
  backend:
    build: ./backend
    container_name: food-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: food-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: food-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foodapp
      MYSQL_USER: fooduser
      MYSQL_PASSWORD: foodpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: